replicaCount: 1
image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent
el:
  host: search-jenkins-logging-2wqjz6new3r5cnx3o4ieeaywla.us-west-2.es.amazonaws.com
  port: 80
service:
  name: nginx
  type: LoadBalancer
  externalPort: 80
  internalPort: 80
backend:
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

